name: Publish Any Commit

on:
  push:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event_name == 'push' || github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new@0.0 publish --compact --pnpm ./
